# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Maven3

on:
  push:
    branches: 
      - master
      - 1.*
    tags:
      - v*
  pull_request:
    branches: 
      - master
      - 1.*

jobs:
  build:
    name: Build chronosQ
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 4
    - name: Maven Test
      run: mvn test
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up Clojars
      uses: actions/setup-java@v3
      with: # running setup-java again overwrites the settings.xml
        distribution: 'zulu'
        java-version: '8.0'
        server-id: clojars # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: CLOJARS_USERNAME # env variable for username in deploy
        server-password: CLOJARS_DEPLOY_TOKEN # env variable for token in deploy

    - name: Publish to clojars
      if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/master') }}
      run: mvn deploy
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_DEPLOY_TOKEN: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
